name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  # Base for the PR
  BASE_REPO: ${{ github.event.pull_request.base.repo.clone_url }}

  # Repository of PR
  PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.clone_url }}


jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.base.repo.clone_url != github.event.pull_request.head.repo.clone_url
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest' ] # 'windows-latest' too flaky
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3

      - name: 'Set up Java'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: 'Cache Maven packages'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test
        uses: coactions/setup-xvfb@v1
        with: 
          run: mvn clean verify -PuseJenkinsSnapshots
          working-directory: org.eclipse.xtext.full.releng
